# Generated by Django 6.0.2 on 2026-02-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0002_tasks_description_alter_tasks_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
