# Generated by Django 6.0.2 on 2026-02-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0003_alter_tasks_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='name',
            new_name='task_name',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='description',
        ),
        migrations.AddField(
            model_name='tasks',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tasks',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
